network/network/urls.py

from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile/<str:name>", views.profile, name="prof"),
    path("following", views.only_following, name="only_follows"),

    # API routes
    path("make-post", views.create_post, name="makepost"),
    path("follow", views.follow, name="to_follow"),
    path("like", views.to_like, name="like")
]

network/project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/network/models.py
from cgitb import text
from email.policy import default
from tkinter import CASCADE, N
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from requests import delete

class User(AbstractUser):
    id = models.BigAutoField(primary_key=True)

class Follows(models.Model):
    id = models.BigAutoField(primary_key=True)
    following = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name="fwing")
    followers = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name="fwers")

    class Meta:
        unique_together = ["following", "followers"]

    def __str__(self):
        return f"{self.followers} follows {self.following}"

class Post(models.Model):
    id = models.BigAutoField(primary_key=True)
    poster = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=1000)
    image = models.URLField(max_length=500, blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)
    
class Like(models.Model):
    id = models.BigAutoField(primary_key=True)
    postID = models.ForeignKey(Post, on_delete=models.CASCADE)
    liker = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ["postID", "liker"]

    def __str__(self):
        return f"Post with {self.postID} liked by {self.liker}"

network/network/views.py
import json
from re import S
from turtle import title
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.core.paginator import Paginator
from django.db.models import OuterRef, Count
from django.views.decorators.csrf import csrf_exempt
from .models import *

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "network/register.html")


def index(request):
    # Pagination, setting the most recent posts to show up first
    if request.user.is_authenticated:
        numof_likes = Like.objects.filter(postID_id=OuterRef('id'), liker_id=request.session["_auth_user_id"])
        p = Post.objects.all().order_by("-date").annotate(num_likes=Count(numof_likes.values("id")))
        print(p)
    else:
        p = Post.objects.all().order_by("-date")

    paginator = Paginator(p, 10)
    page_number = request.GET.get('page')
    eachP = paginator.get_page(page_number)

    return render(request, "network/index.html", {
        "posts": eachP,
        "title": "All posts",
    })

def only_following(request):
    userID = request.session["_auth_user_id"]
    f = Follows.objects.filter(followers_id=userID).values_list("following_id", flat=True)

    # If queryset is empty
    if not f:
        return render(request, "network/index.html", {
        "message": "It seems that you haven't follow anyone yet / None of the people you follow has posted anything.",
        "title": "Following"
    })

    # Pagination
    numof_likes = Like.objects.filter(postID_id=OuterRef('id'), liker_id=request.session["_auth_user_id"])
    p = Post.objects.filter(poster_id__in=f).order_by("-date").annotate(num_likes=Count(numof_likes.values("id")))
    paginator = Paginator(p, 10)
    page_number = request.GET.get('page')
    eachP = paginator.get_page(page_number)

    return render(request, "network/index.html", {
        "posts": eachP,
        "title": "Following"
    })

def create_post(request):
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)

    posted = json.loads(request.body)
    txt = posted.get('text')

    # Make sure post is not empty
    if len(txt) == 0:
        return JsonResponse({
            "error": "User tried to make an empty post."
        }, status=400)

    # Accept post with no image URL    
    img = posted.get('image')
    if len(img) == 0:
        img = None

    choice = posted.get('choice')

    # Check if user wants to create or edit post
    if choice == 'post':
        try:
            sender = int(posted.get('sender'))
            savepost = Post(
                text=txt,
                image=img,
                poster=User.objects.get(id=sender)
            )
            savepost.save()
            return JsonResponse({"message": "Post successfully created"}, status=201)
        except:
            return JsonResponse({"error": "Input value error in creating post."}, status=400)
    elif choice == 'edit':
        try:
            postid = posted.get('postid')
            Post.objects.filter(id=postid).update(text=txt, image=img)
            return JsonResponse({"message": "Post successfully edited", "newtxt": Post.objects.filter(id=postid).values_list("text", flat=True).first(), "newimg": Post.objects.filter(id=postid).values_list("image", flat=True).first() ,"status": 201})
        except:
            return JsonResponse({"error": "Input value error in editing post."}, status=400)
    else:
        return JsonResponse({"error": "Option error in creating/editing post."}, status=400)

def profile(request, name):
    current_user = request.session["_auth_user_id"]
    check_info = User.objects.filter(username=name).values_list("id", flat=True).first()
    info = User.objects.filter(username=name)
    numof_likes = Like.objects.filter(postID_id=OuterRef("id"), liker_id=check_info)
    follow_info = Post.objects.filter(poster_id=check_info).order_by("-date").annotate(num_likes=Count(numof_likes.values("id")))

    # Check if user is checking their own profile
    same = False
    if check_info == int(current_user):
        same = True

    # Count following & followers
    following_count = Follows.objects.filter(followers_id=check_info).count()
    follower_count = Follows.objects.filter(following_id=check_info).count()

    # Check if user already follows the profile they're checking
    already = False
    is_following = Follows.objects.filter(followers_id=current_user).filter(following_id=check_info)
    if is_following.exists():
        already = True

    return render(request, "network/profile.html", {
        "info": info,
        "follow_info": follow_info,
        "followers": follower_count,
        "following": following_count,
        "same": same,
        "already": already
    })

def follow(request):
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)

    info = json.loads(request.body)
    followed = int(info.get('followed'))
    follower = int(info.get('follower'))
    check = info.get('check')

    # Check if user wants to follow/unfollow
    if check == "follow":
        try:
            save_follow = Follows(
                following=User.objects.get(id=followed),
                followers=User.objects.get(id=follower)
            )
            save_follow.save()
            return JsonResponse({"message": "User successfully followed."}, status=201)
        except:
            return JsonResponse({"error": "User already followed."}, status=400)
    elif check == "unfollow":
        try:
            remove = Follows.objects.filter(followers_id=follower).filter(following_id=followed)
            remove.delete()
            return JsonResponse({"message": "User successfully unfollowed."}, status=201)
        except:
            return JsonResponse({"error": "User not followed."}, status=400)
    else:
        return JsonResponse({"error": "Option error."}, status=400)

@csrf_exempt
def to_like(request):
    if request.method == "POST":
        data = json.loads(request.body)
        post = data.get('postid')
        userid = data.get('userid')

        # Remove like if user already liked the post
        check = Like.objects.filter(liker_id=userid).filter(postID_id=post)
        if check.exists():
            check.delete()
            new_total = Like.objects.filter(postID_id=post).count()
            return JsonResponse({"message": "Post successfully unliked.", "numlikes": new_total, "status":201})
        else:
            addlike = Like(
                liker_id = User.objects.filter(id=userid).values_list("id", flat=True).first(),
                postID_id = Post.objects.filter(id=post).values_list("id", flat=True).first()
            )
            addlike.save()
            new_total = Like.objects.filter(postID_id=post).count()
            return JsonResponse({"message": "Post successfully liked.", "numlikes": new_total,"status":201})
    else:
        return JsonResponse({"error": "method is not POST."}, status=400)

network/network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}

    <!-- Posts -->
    <br>
    <h3 style="text-align: center;">{{ title }}</h3>
    <hr>
    <br>
    {% if message %}
        <h4 style="text-align: center;">{{ message }}</h4>
    {% endif %}
    {% for i in posts %}
        <div style="background-color: #bbc2c7;" class="card mb-3">
            {% if not i.image is None %}
            <img  id="currentimg{{ i.id }}" src="{{ i.image }}" class="card-img-top" alt="img" style="max-width: 300px; max-height: 300px; height: auto; width: auto;">
            {% endif %}
            <div class="card-body">
                <p class="card-text" id="currenttxt{{ i.id }}">{{ i.text }}</p>
                <p class="card-text"><small class="text-muted"><a href="{% url 'prof' i.poster %}">{{ i.poster }}</a> at {{ i.date }}</small></p>
                {% if user.is_authenticated %}
                    <i class='bi bi-heart-fill' id="post{{ i.id }}" onclick="add_like('{{ i.id }}', '{{ user.id }}')"></i> <div style="display: inline-block;" id="likes{{ i.id }}">{{ i.like_set.count }}</div>
                {% else %}
                    Likes: {{ i.like_set.count }}
                {% endif %}
                <br><br>
                {% if user.id == i.poster_id %}
                    <button type="button" class="btn btn-primary" value="{{ i.id }}" onclick="edit_form(this.value)">Edit</button>

                    <!-- Edit form -->
                    <div class="show" id="editform{{ i.id }}">
                        <br>
                        <div class="card border-primary">
                            <form method="POST">
                                {% csrf_token %}
                                <h4 class="card-title" style="margin-left: 1.5%;">Edit</h4>
                                <div class="card-body">
                                    <div class="mb-3">
                                        <input type="url" class="form-control" id="editimg{{ i.id }}" placeholder="Image URL here">
                                    </div>
                                    <br>
                                    <div class="mb-3">
                                        <textarea class="form-control" id="edittxt{{ i.id }}" placeholder="Text here"></textarea>
                                    </div>
                                    <input type="hidden" id="thesender{{ i.id }}" value="{{ i.id }}">
                                    <button type="button" id="post_button" class="btn btn-primary" onclick="make_post('Edit', '{{ i.id }}')">Confirm</button>
                                </div>
                            </form>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    {% empty %}
        <h4 style="text-align: center; color: white;">No posts</h4>
    {% endfor %}

    <!-- Pagination -->
    <div class="pagings">
    <nav aria-label="Page navigation example">
        <ul class="pagination">

        {% if posts.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a></li>
        {% endif %}

        <li class="page-item disabled"><a class="page-link" href="#">Page {{ posts.number }} of {{ posts.paginator.num_pages }}</a></li>

        {% if posts.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">Next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ posts.paginator.num_pages }}">Last &raquo;</a></li>
        {% endif %}

        </ul>
    </nav>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'network/index.js' %}"></script>
{% endblock %}

network/network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
        {% block script %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'index' %}">Network</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a style="color: white;" class="nav-link" href="{% url 'index' %}"> All Posts</a>
                      </li>
                  {% if user.is_authenticated %}

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'prof' user.username %}"><strong>{{ user.username }}</strong></a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="#" id="make">Create post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'only_follows' %}">Following</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
                  {% else %}
                
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                  {% endif %}

                
              </div>
            </div>
          </nav>


      
        
          <div class="body">
            <div id="make-post" class="show">
            <br><br>
            <div class="card text-center border-primary">
                <form method="POST">
                    {% csrf_token %}
                    <h4 class="card-title">What's on your mind?</h4>
                    <div class="card-body">
                    <div class="mb-3">
                        <input type="url" class="form-control" id="img" placeholder="Image URL here">
                    </div>
                    <br>
                    <div class="mb-3">
                        <textarea class="form-control" id="txt" placeholder="Text here"></textarea>
                    </div>
                    <input type="hidden" id="sender" value="{{ user.id }}">
                    <input type="submit" id="post_button" class="btn btn-primary" value="Post" onclick="make_post(this.value)">
                    </div>
                </form>
            </div>
            <br>
            </div>
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

network/network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="mb-3">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

network/network/templates/network/profile.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
 
    {% for i in info %}

        <br><br>
        <div class="card text-center border-primary">
            <div style="background-color: white;" class="card-header">Profile</div>
            <div class="body">
                <br>
                <h4 class="card-title">{{ i.username }}</h4>
                <br>
                {% if not same %}
                    <form method="POST">
                        {% csrf_token %}
                        <input type="hidden" id="the_followed" value="{{ i.id }}">
                        <input type="hidden" id="the_follower" value="{{ user.id }}">
                        {% if already %}
                            <button type="submit" class="btn btn-primary" id="follow" value="unfollow" onmousedown="to_follow(this.value)">Unfollow</button>
                        {% else %}
                            <button type="submit" class="btn btn-primary" id="follow" value="follow" onmousedown="to_follow(this.value)">Follow</button>
                        {% endif %}
                    </form>
                    <br>
                {% endif %}
            </div>
            <div style="background-color: white;" class="card-footer">{{ followers }} followers, {{ following }} following</div>
        </div>

    {% endfor %}

    <!-- User's posts -->
    <br><br><hr>
    <h3 style="text-align: center; color: white;">Posts</h3>
    <br>
    {% for i in follow_info %}
        <div  style="background-color: #bbc2c7;"  class="card mb-3 border-primary">
            {% if not i.image is None %}
            <img id="currentimg{{ i.id }}" src="{{ i.image }}" class="card-img-top" alt="img" style="max-width: 300px; max-height: 300px; height: auto; width: auto;">
            {% endif %}
            <div class="card-body">
                <p id="currenttxt{{ i.id }}" class="card-text">{{ i.text }}</p>
                <p class="card-text"><small class="text-muted">Posted at {{ i.date }}</small></p>
                <i class='bi bi-heart-fill' id="post{{ i.id }}" onclick="add_like('{{ i.id }}', '{{ user.id }}')"></i> <div style="display: inline-block;" id="likes{{ i.id }}">{{ i.like_set.count }}</div> <br><br>

                <!-- Show edit form if user is checking their own profile -->
                {% if same %}
                    <button type="button" class="btn btn-primary" value="{{ i.id }}" onclick="edit_form(this.value)">Edit</button>
                    <div class="show" id="editform{{ i.id }}">
                        <br>
                        <div class="card border-primary">
                            <form method="POST">
                                {% csrf_token %}
                                <h4 class="card-title" style="margin-left: 1.5%;">Edit</h4>
                                <div class="card-body">
                                    <div class="mb-3">
                                        <input type="url" class="form-control" id="editimg{{ i.id }}" placeholder="Image URL here">
                                    </div>
                                    <br>
                                    <div class="mb-3">
                                        <textarea class="form-control" id="edittxt{{ i.id }}" placeholder="Text here"></textarea>
                                    </div>
                                    <input type="hidden" id="thesender{{ i.id }}" value="{{ i.id }}">
                                    <button type="button" id="post_button" class="btn btn-primary" onclick="make_post('Edit', '{{ i.id }}')">Confirm</button>
                                </div>
                            </form>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endfor %}


{% endblock %}

{% block script %}
    <script src="{% static 'network/index.js' %}"></script>
{% endblock %}

network/network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="mb-3">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="mb-3">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="mb-3">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}